### ISSUE TITLE
Bitrate/Noisy track flags

### ISSUE THREAD

**Issue by cyancey76** [mxew/firetable-user#115]
We should put in a thing where mods can flag other peoples tracks as low bitrate, noisy, etc. and it marks the tracks in their playlists similar to how we did the broken track flags.

**Comment by chrisrohn** [comment]
This is a great idea

**Comment by ghost** [comment]
maybe tag them so user knows why...
`!flag noize`
`!flag bitrate`
`!flag saccharinechintzypop`

**Comment by mxew** [comment]
Added to hostbot in this commit: https://github.com/mxew/firetable-hostbot/commit/0347c835a5559dc97b60c0e493fe9e7fb8b519c0
