### ISSUE TITLE
Update Emojis in Picker

### ISSUE THREAD

**Issue by andrewgtibbetts** [mxew/firetable-user#152]
New emojis have been released and are available but aren't in the picker options. e.g. 🤏

**Comment by mxew** [comment]
We use https://github.com/muan/emojilib for the :shortcode: mapping and emoji picker. We'll need to update from v2.x to v3.x for the new emoji/shortcode pairs.

**Comment by mxew** [comment]
Looks like in v3.x all metadata other than the keyword lists has been removed from emojilib and is now found in a separate package https://github.com/muan/unicode-emoji-json. Only thing we actually use that is now moved to the new package is the categories (that's how we sort the emojis into categories for the picker).
